"""Add lore items table

Revision ID: 7cb338b218a2
Revises: 45cfb22a1630
Create Date: 2026-02-13 17:22:30.581091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cb338b218a2'
down_revision: Union[str, None] = '45cfb22a1630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lore_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('first_appearance_chapter_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['first_appearance_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lore_items_category'), 'lore_items', ['category'], unique=False)
    op.create_index(op.f('ix_lore_items_id'), 'lore_items', ['id'], unique=False)
    op.create_index(op.f('ix_lore_items_name'), 'lore_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lore_items_name'), table_name='lore_items')
    op.drop_index(op.f('ix_lore_items_id'), table_name='lore_items')
    op.drop_index(op.f('ix_lore_items_category'), table_name='lore_items')
    op.drop_table('lore_items')
    # ### end Alembic commands ###
